<?php
/**
 * Created by PhpStorm.
 * User: xiang.chen
 * Date: 2015/11/26
 * Time: 15:04
 */
$spconf = $GLOBALS['config']['SPHINX_CASDATA_HOST'];
$spconf = explode(':', $spconf);
return [
    'host'      => $spconf[0],
    'port'      => $spconf[1],
    'timeout'   => 2000,
    'max_limit' => 1000,
    'indexes'   => [
        'casdata' => array('table' => 'sph_cas_data', 'column' => 'cas_dataid'),
    ],
    'filter_words'=>[
        1 => [
            'alpha' => 'α',
            'beta' => 'β',
            'gamma' => 'γ',
            'delta' => 'δ',
            'epsilon' => 'ε',
            'digamma' => 'ϝ',
            'zeta' => 'ζ',
            'eta' => 'η',
            'theta' => 'θ',
            'lambda' => 'λ',
            'mu' => 'μ',
            'xi' => 'ξ',
            'pi' => 'Ππ',
            'rho' => 'ρ',
            'sigma' => 'σ',
            'phi' => 'φ',
            'psi' => 'ψ',
            'omega' => 'ω',
        ],
        2 => [
            'inquiry',
            'price',
            'supplier',
            'supply',
            'purchase',
            'purity',
            'global purchse',
            'stock',
            'suppliers',
            'producer',
            'product',
            'products',
            'order',
            'solution',
            'property',
            'phone',
            'call',
            'contact',
            'package',
            '价格',
            '库存',
            '供应',
            '供应商',
            '生产商',
            '厂家',
            '生产',
            '公司',
            '平台',
            '采购',
            '产品',
            '订货',
            '订购',
            '配送',
            '咨询',
            '查询',
            '报价',
            '批发',
            '溶液',
            '性质',
            '电话',
            '联系电话',
            '规格',
            '询盘',
            '纯度',
        ],
    ],
    'weights' => [
        'name_cn' => 18000,
        'mol_name' => 18000,
        'synonyms' => 10,
        'goods_name' => 800,
        'goods_english_name' => 800,
        'formula' => 5000,
        'cas_number' => 5000,
        'synonyms1' => 3000,
        'synonyms2' => 3000,
        'synonyms3' => 3000,
        'synonyms4' => 3000,
        'synonyms5' => 3000,
        'synonyms6' => 3000,
        'synonyms7' => 3000,
        'synonyms8' => 3000,
        'synonyms9' => 3000,
        'synonyms10' => 3000,
        'synonyms11' => 3000,
        'synonyms12' => 3000,
        'synonyms13' => 3000,
        'synonyms14' => 3000,
        'synonyms15' => 3000,
        'synonyms16' => 3000,
        'synonyms17' => 3000,
        'synonyms18' => 3000,
        'synonyms19' => 3000,
        'synonyms20' => 3000,
        'synonyms21' => 3000,
        'synonyms22' => 3000,
        'synonyms23' => 3000,
        'synonyms24' => 3000,
        'synonyms25' => 3000
    ]
];